# Generated by Django 4.0.5 on 2022-06-24 06:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_restaurant_average_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="resturant",
            new_name="restaurant",
        ),
    ]
