# Generated by Django 4.0.5 on 2022-06-25 10:40
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_rename_resturant_menu_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_image",
                to="restaurant.restaurant",
            ),
        ),
    ]
